import Foundation
import SwiftUI
import UniformTypeIdentifiers
import SwiftData

struct AccountingBackup: Codable { var formatVersion: Int = 1; var exportedAt: Date = Date(); var accounts: [AccountRecord]; var categories: [CategoryRecord]; var transactions: [TransactionRecord] }
struct AccountRecord: Codable { var id: UUID; var name: String; var typeRawValue: String; var currencyCode: String; var openingBalance: Decimal; var isLiability: Bool; var createdAt: Date }
struct CategoryRecord: Codable { var id: UUID; var name: String; var icon: String; var isIncome: Bool; var colorHex: String }
struct PostingRecord: Codable { var id: UUID; var accountName: String; var amount: Decimal; var memo: String }
struct TransactionRecord: Codable { var id: UUID; var date: Date; var payee: String; var note: String; var currencyCode: String; var source: String; var createdAt: Date; var postings: [PostingRecord] }
enum ImportConflict: String, CaseIterable, Identifiable { case merge = "合并（保留现有数据）"; case overwrite = "覆盖同 ID 数据"; case replaceAll = "清空后恢复"; var id: String { rawValue } }
enum DataTransferError: LocalizedError { case invalidBackup; case unbalancedTransaction(String); var errorDescription: String? { switch self { case .invalidBackup: return "文件不是有效的 51 记账备份。"; case .unbalancedTransaction(let payee): return "交易“\(payee)”借贷不平衡，已停止导入。" } } }
struct AccountingFileDocument: FileDocument { static var readableContentTypes: [UTType] { [.data, .json, .plainText] }; static var writableContentTypes: [UTType] { [.data, .json, .plainText] }; var data: Data; init(data: Data = Data()) { self.data = data }; init(configuration: ReadConfiguration) throws { data = configuration.file.regularFileContents ?? Data() }; func fileWrapper(configuration: WriteConfiguration) throws -> FileWrapper { FileWrapper(regularFileWithContents: data) } }
struct DataTransferService {
 static let encoder: JSONEncoder = { let e = JSONEncoder(); e.outputFormatting = [.prettyPrinted, .sortedKeys]; e.dateEncodingStrategy = .iso8601; return e }(); static let decoder: JSONDecoder = { let d = JSONDecoder(); d.dateDecodingStrategy = .iso8601; return d }()
 static func backup(accounts: [Account], categories: [Category], transactions: [BookkeepingTransaction]) throws -> Data { try encoder.encode(AccountingBackup(accounts: accounts.map { AccountRecord(id: $0.id, name: $0.name, typeRawValue: $0.typeRawValue, currencyCode: $0.currencyCode, openingBalance: $0.openingBalance, isLiability: $0.isLiability, createdAt: $0.createdAt) }, categories: categories.map { CategoryRecord(id: $0.id, name: $0.name, icon: $0.icon, isIncome: $0.isIncome, colorHex: $0.colorHex) }, transactions: transactions.map { t in TransactionRecord(id: t.id, date: t.date, payee: t.payee, note: t.note, currencyCode: t.currencyCode, source: t.source, createdAt: t.createdAt, postings: t.postings.map { PostingRecord(id: $0.id, accountName: $0.accountName, amount: $0.amount, memo: $0.memo) }) })) }
 static func readBackup(_ data: Data) throws -> AccountingBackup { guard let value = try? decoder.decode(AccountingBackup.self, from: data), value.formatVersion == 1 else { throw DataTransferError.invalidBackup }; return value }
 static func restore(_ backup: AccountingBackup, in context: ModelContext, conflict: ImportConflict) throws { let accounts = try context.fetch(FetchDescriptor<Account>()); let categories = try context.fetch(FetchDescriptor<Category>()); let transactions = try context.fetch(FetchDescriptor<BookkeepingTransaction>()); if conflict == .replaceAll { transactions.forEach(context.delete); accounts.forEach(context.delete); categories.forEach(context.delete) }; let accountIDs = Set(accounts.map(\.id)); let categoryIDs = Set(categories.map(\.id)); let transactionByID = Dictionary(uniqueKeysWithValues: transactions.map { ($0.id, $0) }); for x in backup.accounts where conflict == .replaceAll || (conflict == .merge && !accountIDs.contains(x.id)) { let m = Account(name: x.name, type: AccountType(rawValue: x.typeRawValue) ?? .asset, currencyCode: x.currencyCode, openingBalance: x.openingBalance, isLiability: x.isLiability); m.id = x.id; m.createdAt = x.createdAt; context.insert(m) }; for x in backup.categories where conflict == .replaceAll || (conflict == .merge && !categoryIDs.contains(x.id)) { let m = Category(name: x.name, icon: x.icon, isIncome: x.isIncome, colorHex: x.colorHex); m.id = x.id; context.insert(m) }; for x in backup.transactions { let postings = x.postings.map { Posting(accountName: $0.accountName, amount: $0.amount, memo: $0.memo) }; let candidate = BookkeepingTransaction(date: x.date, payee: x.payee, note: x.note, currencyCode: x.currencyCode, source: x.source, postings: postings); candidate.id = x.id; candidate.createdAt = x.createdAt; guard case .success = TransactionValidator.validate(candidate) else { throw DataTransferError.unbalancedTransaction(x.payee) }; if conflict == .overwrite, let existing = transactionByID[x.id] { existing.date = x.date; existing.payee = x.payee; existing.note = x.note; existing.currencyCode = x.currencyCode; existing.source = x.source; existing.postings = postings } else if conflict == .replaceAll || (conflict == .merge && transactionByID[x.id] == nil) { context.insert(candidate) } }; try context.save() }
 static func beancount(_ transactions: [BookkeepingTransaction]) -> Data { Data(BeancountExporter().export(transactions).utf8) }
 static func csv(_ transactions: [BookkeepingTransaction]) -> Data { Data("id,date,payee,note,currency,source,account,amount,memo\n".utf8) }
}
