import Foundation

struct BackupConfiguration: Codable { var webDAVURL: URL?; var webDAVUsername: String?; var webDAVPassword: String?; var githubOwner: String?; var githubRepository: String?; var githubToken: String? }
actor BackupManager {
 func localExport(transactions: [BookkeepingTransaction]) throws -> Data { let records = transactions.map { ["编号": $0.id.uuidString, "日期": ISO8601DateFormatter().string(from: $0.date), "商户": $0.payee, "备注": $0.note] }; return try JSONSerialization.data(withJSONObject: records, options: [.prettyPrinted, .sortedKeys]) }
 func uploadWebDAV(data: Data, filename: String, configuration: BackupConfiguration) async throws { guard let base = configuration.webDAVURL else { throw URLError(.badURL) }; var r = URLRequest(url: base.appendingPathComponent(filename), timeoutInterval: 30); r.httpMethod = "PUT"; r.httpBody = data; r.setValue("application/octet-stream", forHTTPHeaderField: "Content-Type"); if let u = configuration.webDAVUsername, let p = configuration.webDAVPassword { r.setValue("Basic \(Data("\(u):\(p)".utf8).base64EncodedString())", forHTTPHeaderField: "Authorization") }; let (_, response) = try await URLSession.shared.data(for: r); guard let h = response as? HTTPURLResponse, (200..<300).contains(h.statusCode) else { throw URLError(.badServerResponse) } }
 func githubCommit(data: Data, filename: String, configuration: BackupConfiguration) async throws { guard let owner = configuration.githubOwner, let repo = configuration.githubRepository, let token = configuration.githubToken else { throw URLError(.userAuthenticationRequired) }; let url = URL(string: "https://api.github.com/repos/\(owner)/\(repo)/contents/\(filename)")!; var r = URLRequest(url: url, timeoutInterval: 30); r.httpMethod = "PUT"; r.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization"); r.setValue("application/vnd.github+json", forHTTPHeaderField: "Accept"); r.setValue("application/json", forHTTPHeaderField: "Content-Type"); var body: [String: Any] = ["message": "备份 51 账务数据", "content": data.base64EncodedString()]; if let existing = try? await currentSHA(url: url, token: token) { body["sha"] = existing }; r.httpBody = try JSONSerialization.data(withJSONObject: body); let (_, response) = try await URLSession.shared.data(for: r); guard let h = response as? HTTPURLResponse, (200..<300).contains(h.statusCode) else { throw URLError(.badServerResponse) } }
 private func currentSHA(url: URL, token: String) async throws -> String { var r = URLRequest(url: url, timeoutInterval: 30); r.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization"); let (d, resp) = try await URLSession.shared.data(for: r); guard let h = resp as? HTTPURLResponse, h.statusCode == 200, let json = try JSONSerialization.jsonObject(with: d) as? [String: Any], let sha = json["sha"] as? String else { throw URLError(.fileDoesNotExist) }; return sha }
 func saveToICloud(data: Data, filename: String) throws { guard let url = FileManager.default.url(forUbiquityContainerIdentifier: nil)?.appendingPathComponent(filename) else { throw CocoaError(.fileNoSuchFile) }; try data.write(to: url, options: .atomic) }
}
